export const categories: Category[] = [
	{
		id: 1,
		name: "Transportation",
		backgroundColor: "#127e1a",
		iconUrl: "https://example.com/tristique/est/et/tempus/semper/est/quam.js",
	},
	{
		id: 2,
		name: "Food",
		backgroundColor: "#1031df",
		iconUrl:
			"https://example.com/semper/interdum/mauris/ullamcorper/purus.html",
	},
	{
		id: 3,
		name: "Repair",
		backgroundColor: "#b19282",
		iconUrl: "https://example.com/tincidunt.jsp",
	},
	{
		id: 4,
		name: "Construction",
		backgroundColor: "#368535",
		iconUrl: "https://example.com.com.cn/dapibus/duis/at/velit.jpg",
	},
	{
		id: 5,
		name: "Technology",
		backgroundColor: "#647608",
		iconUrl: "https://example.com/tincidunt/ante/vel/ipsum/praesent.html",
	},
	{
		id: 6,
		name: "Health Care",
		backgroundColor: "#645555",
		iconUrl: "https://example.com/tincidunt/ante/vel/ipsum/praesent.html",
	},
];

export const businesses: Business[] = [
	{
		id: 1,
		name: "Grady-Dibbert",
		description:
			"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
		address: "35559 Express Trail",
		category: "Technology",
		contactPerson: "Hendrik Franklen",
		email: "dmerck0@nifty.com",
		images: [{ url: "https://dummyimage.com/171x100.png/cc0000/ffffff" }],
	},
	{
		id: 2,
		name: "Frami Group",
		description:
			"Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
		address: "11072 Dexter Parkway",
		category: "Food",
		contactPerson: "Shanie Beahan",
		email: "mdaborne1@360.cn",
		images: [{ url: "https://dummyimage.com/190x100.png/cc0000/ffffff" }],
	},
	{
		id: 3,
		name: "Auer-Bogan",
		description:
			"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
		address: "81 Clyde Gallagher Terrace",
		category: "Transportation",
		contactPerson: "Jerrilee Matieu",
		email: "jcordeiro2@altervista.org",
		images: [{ url: "https://dummyimage.com/218x100.png/cc0000/ffffff" }],
	},
	{
		id: 4,
		name: "Spencer LLC",
		description:
			"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
		address: "167 Esch Park",
		category: "Repair",
		contactPerson: "Susann Sawley",
		email: "asnaith3@yandex.ru",
		images: [{ url: "https://dummyimage.com/116x100.png/5fa2dd/ffffff" }],
	},
	{
		id: 5,
		name: "Nienow Group",
		description:
			"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
		address: "18806 Sycamore Alley",
		category: "Construction",
		contactPerson: "Mair O'Kerin",
		email: "lbannister4@qq.com",
		images: [{ url: "https://dummyimage.com/230x100.png/cc0000/ffffff" }],
	},
	{
		id: 6,
		name: "O'Connell-Strosin",
		description:
			"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
		address: "2308 Emmet Plaza",
		category: "Health Care",
		contactPerson: "Vivyanne Wickins",
		email: "rmatej5@smugmug.com",
		images: [{ url: "http://dummyimage.com/238x100.png/5fa2dd/ffffff" }],
	},
	{
		id: 7,
		name: "Russel and Sons",
		description:
			"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
		address: "40 Birchwood Drive",
		category: "Repair",
		contactPerson: "Josy Pulsford",
		email: "jgermaine6@businessweek.com",
		images: [{ url: "https://dummyimage.com/123x100.png/cc0000/ffffff" }],
	},
	{
		id: 8,
		name: "Mayer LLC",
		description:
			"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
		address: "56440 Milwaukee Way",
		category: "Food",
		contactPerson: "Donal Lapidus",
		email: "avanderdaal7@amazon.co.jp",
		images: [{ url: "https://dummyimage.com/227x100.png/ff4444/ffffff" }],
	},
	{
		id: 9,
		name: "Pouros LLC",
		description:
			"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
		address: "22176 Doe Crossing Crossing",
		category: "Transportation",
		contactPerson: "Joby Seegar",
		email: "cpursey8@skyrock.com",
		images: [{ url: "https://dummyimage.com/144x100.png/5fa2dd/ffffff" }],
	},
	{
		id: 10,
		name: "Schulist, Lind and McCullough",
		description:
			"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
		address: "3 Dakota Lane",
		category: "Technology",
		contactPerson: "Luce Cyson",
		email: "rbreyt9@webnode.com",
		images: [{ url: "https://dummyimage.com/230x100.png/cc0000/ffffff" }],
	},
];

export const bookings: Booking[] = [
	{
		id: 1,
		businessId: 1,
		date: new Date("2024-03-06T12:18"),
		time: "12:18",
		userEmail: "qcoppo0@technorati.com",
		userName: "mhanselmann0",
		status: "Booked",
	},
	{
		id: 2,
		businessId: 2,
		date: new Date("2024-01-01T15:58"),
		time: "15:58",
		userEmail: "tdicarlo1@twitter.com",
		userName: "bsouch1",
		status: "Pending",
	},
	{
		id: 3,
		businessId: 3,
		date: new Date("2024-03-04T11:23"),
		time: "11:23",
		userEmail: "tsugg2@freewebs.com",
		userName: "jfish2",
		status: "Completed",
	},
	{
		id: 4,
		businessId: 4,
		date: new Date("2024-04-17 12:40"),
		time: "12:40",
		userEmail: "nbottelstone3@intel.com",
		userName: "hdenisyev3",
		status: "Booked",
	},
	{
		id: 5,
		businessId: 5,
		date: new Date("2024-08-05T13:06"),
		time: "13:06",
		userEmail: "aeatttok4@tuttocitta.it",
		userName: "jbusswell4",
		status: "Completed",
	},
	{
		id: 6,
		businessId: 6,
		date: new Date("2024-04-16T11:36"),
		time: "11:36",
		userEmail: "djacqueme5@nifty.com",
		userName: "lworledge5",
		status: "Completed",
	},
	{
		id: 7,
		businessId: 7,
		date: new Date("2024-01-16T13:38"),
		time: "13:38",
		userEmail: "egallamore6@ezinearticles.com",
		userName: "mbraunston6",
		status: "Completed",
	},
	{
		id: 8,
		businessId: 8,
		date: new Date("2024-09-08T16:38"),
		time: "16:30",
		userEmail: "hsitford7@dailymotion.com",
		userName: "wcastan7",
		status: "Booked",
	},
	{
		id: 9,
		businessId: 9,
		date: new Date("2024-05-20T15:16"),
		time: "15:16",
		userEmail: "bjermy8@go.com",
		userName: "jwhetson8",
		status: "Booked",
	},
	{
		id: 10,
		businessId: 10,
		date: new Date("2024-09-27T16:49"),
		time: "16:49",
		userEmail: "emioni9@edublogs.org",
		userName: "lmaker9",
		status: "Booked",
	},
];
